spring:
  config:
    activate.on-profile: dev
    import: classpath:monitoring-config.yml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data.mongodb:
    host: ${MONGO_HOST}
    port: ${MONGO_PORT}
    database: ${MONGO_DATABASE}
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    authentication-database: ${MONGO_AUTH_DATABASE}

springdoc:
  dev-server-url: ${DEV_SERVER_URL}
  prod-server-url: ${PROD_SERVER_URL}

osrm.url: ${OSRM_URL}
admin:
  token: ${ADMIN_TOKEN}
  kakao-map-api-key: ${ADMIN_KAKAO_MAP_API_KEY}
notice.base-url: ${BASE_URL}
jwt.secret-key: ${JWT_SECRET_KEY}
