spring:
  application.name: coursepick
  data:
    mongodb:
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

server:
  tomcat.max-part-count: 500
  forward-headers-strategy: framework
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2KB

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

notice:
  base-url: ${BASE_URL}
