spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3307/coursepick
    username: user
    password: secret
  data.mongodb:
    host: localhost
    port: 27017
    database: coursepick
    username: root
    password: secret
    authentication-database: admin

admin:
  token: secret
  kakao-map-api-key: ${ADMIN_KAKAO_MAP_API_KEY}
