spring:
  config.activate.on-profile: local
  data.mongodb:
    host: localhost
    port: 27017
    database: coursepick
    username: root
    password: secret
    authentication-database: admin

springdoc:
  dev-server-url: ${DEV_SERVER_URL:http://localhost:8080}
  prod-server-url: ${PROD_SERVER_URL:http://localhost:8080}

admin:
  token: secret
  kakao-map-api-key: dummy-api-key
notice.base-url: http://localhost:8080/images
jwt.secret-key: secret+secret+secret+secret+secret+secret+secret+secret+secret
