spring:
  config.activate.on-profile: local
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  datasource:
    url: jdbc:mysql://localhost:3307/coursepick
    username: user
    password: secret
  data.mongodb:
    host: localhost
    port: 27017
    database: coursepick
    username: root
    password: secret
    authentication-database: admin

server:
  tomcat:
    max-part-count: 500

admin:
  token: secret
  kakao-map-api-key: dummy-api-key
notice.base-url: http://localhost:8080/images
